mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
  path('', include('piggybox.urls')),
  path('admin/', admin.site.urls),
  path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

piggybox/urls.py
from django.urls import path
from . import views

app_name = 'piggybox'

urlpatterns = [
    path('', views.index, name='index'),
    path('mypage/', views.WishListView.as_view(), name="mypage"),
    path('mypage/calendar/', views.CalendarByUserView.as_view(), name='calendar'),
    path('mypage/calendar/create/', views.DealCreate.as_view(), name='deal-create'),
    path('mypage/calendar/<int:pk>/delete/', views.DealDelete.as_view(), name='deal-delete'),
    path('mypage/calendar/<int:pk>/update/', views.DealUpdate.as_view(), name='deal-update'),
    path('mypage/calendar/<int:year>/<int:month>/', views.CalendarByUserView.as_view(), name='calendar'),
    path('mypage/wishlist/create/', views.WishlistCreate.as_view(), name="wishlist-create"),
    path('signup/', views.SignUp.as_view(), name='signup'),
    
]

piggybox/models.py
import datetime
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone

class Deal(models.Model):
  CATEGORY_LABEL = (
    ('poc', 'おこずかい'),
    ('sal', '給与'),
    ('oti', 'その他所得'),
    ('foo', '食費'),
    ('boo', '教育'),
    ('tra', '交通費'),
    ('sho', 'ショッピング'),
    ('prs', 'プレゼント'),
    ('ent', '交際費'),
    ('fee', '手数料'),
    ('oto', 'その他消費'),
  )

  # define 
  date = models.DateField('日付', default=timezone.now)
  in_out = models.IntegerField('収支', validators=[MinValueValidator(-999999), MaxValueValidator(999999)])
  category = models.CharField(
    'カテゴリー',
    choices=CATEGORY_LABEL,
    default='foo',
    max_length=3,
  )
  description = models.CharField('内容', blank=True, max_length=50)

  user = models.ForeignKey(
    User,
    on_delete=models.SET_NULL,
    null=True,
  )

  def __str__(self):
    return self.description

class Wishlist(models.Model):
  name = models.CharField('名前', max_length=100)
  image = models.ImageField('画像', upload_to='images/', blank=True)
  price = models.IntegerField('価格',
    validators=[
      MinValueValidator(0),
      MaxValueValidator(9999999)
    ],
    blank=True,
  )
  term = models.IntegerField('期間',
    validators=[
      MinValueValidator(1),
      MaxValueValidator(3653)
    ],
    blank=True,
  )
  url = models.CharField('URL', max_length=255, blank=True)
  created_at = models.DateTimeField('作成日', auto_now_add=True)
  memo = models.TextField(
    '備考',
    blank=True,
    max_length=300,
    )

  user = models.ForeignKey(
    User,
    on_delete=models.SET_NULL,
    null=True,
  )

piggybox/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Deal, Wishlist

class DealForm(forms.ModelForm):
  class Meta:
    model = Deal
    fields = ['date', 'in_out', 'category', 'summary']

class SignUpForm(UserCreationForm):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    # HTMLの表示を変更可能にします
    self.fields['username'].widget.attrs['class'] = 'form-control'
    self.fields['username'].widget.attrs['placeholder'] = 'ニックネーム'
    self.fields['email'].widget.attrs['class'] = 'form-control'
    self.fields['email'].widget.attrs['placeholder'] = 'hogehoge@example.com'
    self.fields['password1'].widget.attrs['class'] = 'form-control'
    self.fields['password1'].widget.attrs['placeholder'] = 'パスワード (8文字以上)'
    self.fields['password2'].widget.attrs['class'] = 'form-control'
    self.fields['password2'].widget.attrs['placeholder'] = 'パスワード (確認用)'

  class Meta:
    model = User
    fields = ('username', 'email', 'password1', 'password2')

class WishlistForm(forms.ModelForm):
  class Meta:
    model = Wishlist
    fields = ['name', 'image', 'price', 'term', 'url', 'memo']

piggybox/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView, DeleteView, ListView, TemplateView, UpdateView

from .forms import DealForm, SignUpForm, WishlistForm
from .mixins import BudgetPerDayMixin, MonthCalendarMixin, MonthWithScheduleMixin
from .models import Deal, Wishlist

class DealCreate(CreateView):
    model = Deal
    form_class = DealForm
    success_url = reverse_lazy('piggybox:calendar')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(DealCreate, self).form_valid(form)

class DealUpdate(UpdateView):
    model = Deal
    fields = ['date', 'in_out', 'category', 'summary']

class DealDelete(DeleteView):
    model = Deal
    success_url = reverse_lazy('piggybox:calendar')

class CalendarByUserView(LoginRequiredMixin, MonthWithScheduleMixin, TemplateView):
    """スケジュール付きの月間カレンダーを表示するビュー"""
    model = Deal
    template_name = 'piggybox/calendar.html'
    date_field = 'date'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_month_calendar()
        context.update(calendar_context)
        return context

class SignUp(CreateView):
  form_class = SignUpForm
  template_name = "piggybox/signup.html" 
  success_url = reverse_lazy('piggybox:mypage')

  def form_valid(self, form):
    user = form.save()
    login(self.request, user)
    self.object = user 
    return HttpResponseRedirect(self.get_success_url())

class WishlistCreate(CreateView):
  model = Wishlist
  form_class = WishlistForm
  success_url = reverse_lazy('piggybox:mypage')

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super(DealCreate, self).form_valid(form)

class WishListView(LoginRequiredMixin, BudgetPerDayMixin, ListView):
  model = Wishlist
  template_name = "piggybox/mypage.html"

  def get_context_data(self):
    # コンテキストを取得するために, まずベースとなる実装を呼び出します
    context = super(WishListView, self).get_context_data()
    list_context = list(self.get_queryset().values())
    # 任意のデータを作成してコンテキストに追加します
    for wishlist in list_context:
      price = wishlist['price']
      target_date = wishlist['target_date']
      created_at = wishlist['created_at']

      wishlist['goal_days']   = (target_date-created_at).days
      wishlist['goal_weeks']  = int(wishlist['goal_days']/7)
      wishlist['goal_months'] = int(wishlist['goal_days']/28)
    
      wishlist['goal_per_day'] = int(price/wishlist['goal_days'])
      wishlist['goal_per_week'] = min(wishlist['goal_per_day']*7, price)
      wishlist['goal_per_month'] = min(wishlist['goal_per_day']*28, price)

    print(context)
    return context

  def get_queryset(self):
    return Wishlist.objects.all()

def index(request):
    return render(request, "piggybox/index.html")

piggybox/templates/piggybox/base_generic.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">

  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <!-- bootstrap -->
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <script src="//cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>

  <title>piggybox</title>
</head>

<body>
  <header>
    {% block header %}
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li>
          <h2 style="color:var(--main-color-dark)">piggybox</h2>
        </li>
        <li><a href="{% url 'piggybox:mypage' %}">マイページ</a></li>
        <li><a href="{% url 'piggybox:calendar' %}">貯金する</a></li>
        <li>{{ user.get_username }}</li>
        <li><a class="btn -XS" href="{% url 'logout'%}?next={{request.path}}">ログアウト</a></li>
        {% else %}　
        <li>
          <h1></h1>
        </li>
        <li><a class="btn -XS" href="{% url 'login' %}">ログイン</a></li>
        {% endif %}
      </ul>
    </nav>

    {% endblock %}
  </header>

  <main>
    {% block content %}{% endblock %}
  </main>

  <footer>
    {% block footer %}
    <ul>
      <li><a href="{% url 'piggybox:index' %}">
          <img src="{%static 'img/favicon.png' %}" alt="img/png">
        </a></li>
      <li><a href="{% url 'piggybox:mypage' %}">マイページ</a></li>
      <li><a href="{% url 'piggybox:calendar' %}">貯金する</a></li>
      <li><a href="#Contact">お問い合わせ</a></li>
      <li>
        <div id="langChenge">
          <input type="radio" name="land" id="langJa" checked>Ja
          /
          <input type="radio" name="land" id="langEn">En
        </div>
      </li>
    </ul>
    <p>@2021 Shunya Asano</p>
    {% endblock %}
  </footer>

</body>

piggybox/templates/piggybox/calendar.html
{% extends 'piggybox/base_generic.html' %}
{% block content %}
<style>
  #calendar {
    height: 50vh;
    margin: 5vh auto;
    overflow: auto;
  }

  .arrow {
    display: inline-block;
    padding: 0 1rem;
    position: relative;
    vertical-align: middle;
  }

  .arrow::before,
  .arrow::after {
    bottom: 0;
    box-sizing: border-box;
    content: "";
    left: 0;
    margin: auto;
    position: absolute;
    top: 0;
    vertical-align: middle;
  }

  .arrow::before {
    width: 2rem;
    height: 2rem;
    border: .1rem solid var(--sub-color);
    -webkit-border-radius: 50%;
    border-radius: 50%;
  }

  .arrow::after {
    border: .75rem solid transparent;
    height: .7vw;
    width: .7vw;
  }

  .arrow-left::after {
    border-right: .7rem solid var(--sub-color);
    left: -.2rem;
  }

  .arrow-right::after {
    border-left: .7rem solid var(--sub-color);
    left: .8rem;
  }

  table {
    table-layout: fixed;
    overflow: auto;
  }
  
  table>tr{
    position: absolute;
  }

  td>label {
    height: 100px;
    overflow: hidden;
    white-space: nowrap;
  }

  td p {
    font-size: .1vw;
  }

  td input[type=radio]{
    cursor: pointer;
  }
</style>

<h2>
  <a class="arrow arrow-left" href="{% url 'piggybox:calendar' month_previous.year month_previous.month %}"></a>
  {{ month_current | date:"Y年m月" }}
  <a class="arrow arrow-right" href="{% url 'piggybox:calendar' month_next.year month_next.month %}"></a>
</h2>

<div id="calendar">
  <table class="table">
    <thead>
      <tr>
        {% for w in week_names %}
        <th>{{ w }}</th>
        {% endfor %}
      </tr>
    </thead>
    <tbody id="SelectedDay">
      {% for week_day_schedles in month_day_schedules %}
      <tr>
        {% for day, schedules in week_day_schedles.items %}
        {% if now == day %}
        <td class="table-success">
        {% else %}
        <td>
        {% endif %}
          <label>
            {% if month_current.month == day.month %}
            <input type="radio" name="selected-day" value="{{ day.day }}" onclick="getRadioValue('selected-day');">
            {{ day.day }}
            {% endif %}

            {% for schedule in schedules %}
            {% if schedule.in_out > 0 %}
            <p style="color:blue">
              {% else %}
            <p style="color:red">
              {% endif %}
              {{ schedule.in_out }}
            </p>
            {% endfor %}
          </label>
        </td>
        {% endfor %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<a class="btn -S" href="{% url 'piggybox:deal-create' %}">
  <h2>追加</h2>
</a>

<script>
function getRadioValue(name){
  //ラジオボタンオブジェクトを取得する
  var radios = document.getElementsByName(name);
 
  //取得したラジオボタンオブジェクトから選択されたものを探し出す
  var result;
  for(var i=0; i<radios.length; i++){
    if (radios[i].checked) {
      //選択されたラジオボタンのvalue値を取得する
      result = radios[i].value;
      break;
    }
  }
 
  //value値を表示する
  alert("value値は" + result + "です");
}
</script>
{% endblock %}

piggybox/templates/piggybox/deal_confirm_delete.html
{% extends "piggybox/base_generic.html" %}

{% block content %}

<h1>著者の削除</h1>

<p>本当に著者を削除してよろしいですか: {{ author }}？</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="はい、削除します。" class="btn">
</form>

{% endblock %}

piggybox/templates/piggybox/deal_form.html
{% extends "piggybox/base_generic.html" %}

{% block content %}
<p style="color:var(--main-color-dark)">piggybox</p>

<div class="form">
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="登録" class="btn">
  </form>
</div>
{% endblock %}

piggybox/templates/piggybox/index.html
{% extends 'piggybox/base_generic.html' %}
{% load static %}

{% block header %}{% endblock %}

{% block content %}
<p class="font-L" style="color:var(--main-color-dark)">piggybox</p>
<img src="{% static 'img/Savings-pana.png' %}" alt="piggybox" style="width: 60vw;">
<h1>What for do you save money?</h1>
<p>あなたの貯金を管理する最もシンプルな方法。</p>
<p>あなたの欲しいものは何ですか？</p>
<a class="btn -M"
  {% if user.is_authenticated %}
    href="{% url 'piggybox:mypage' %}"
  {% else %}
    href="{% url 'piggybox:signup' %}"
  {% endif %}>
  <h2>貯金箱を作る</h2>
</a>
{% endblock %}

piggybox/templates/piggybox/mypage.html
{% extends 'piggybox/base_generic.html' %}
{% load humanize %}
{% block content %}
<style>
  #Wishlist{
    margin: 0 auto;
    overflow-x: auto;
    white-space: nowrap;
    -webkit-overflow-scrolling: touch;
  }

  #Wishlist ul{
    display: inline-block;
    margin: 0 2vw;
  }

  #Wishlist ul li {
    width: 33vw;
  }

  #Wishlist ul li img {
    width: 100%;
  }
</style>
<h1 class="font-M color-midlight">MYPAGE</h1>

{% if wishlist_list %}
<div id="Wishlist">
  {% for wish in wishlist_list %}
    <ul>
      <li>
        <h2>{{ wish.name }}</h2>
        {% if wish.image %}
        <img src="{{ IMAGE_URL }}{{ wish.image.url }}">
        {% endif %}
        <h1>¥{{ wish.price |intcomma }}</h1>
        <p>目標達成まで {{ wish.goal_days |intcomma }} 日！</p>
        <p>1日あたり¥{{ wish.goal_per_day |intcomma}}を貯金</p>
        <p>1週間あたり¥{{ wish.goal_per_week |intcomma}}を貯金</p>
        <p>1ヶ月あたり¥{{ wish.goal_per_month |intcomma}}を貯金</p>
      </li>
    </ul>
  {% endfor %}
</div>

{% else %}
<p>まだ欲しいものが登録されていません。</p>
{% endif %}
{% endblock %}

piggybox/templates/piggybox/signup.html
{% extends "piggybox/base_generic.html" %}

{% block content %}
<p style="color:var(--main-color-dark)">piggybox</p>
<div class="form">
  <p class="font-M">Sign Up</p>
  {% if not next %}
    <p class="text-danger">パスワードが短過ぎるか、一致していません。</p>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form.username }}
    {{ form.email }}
    {{ form.password1 }}
    {{ form.password2 }}
    <input type="submit" value="新規登録" class="btn -M" >
    <input type="hidden" name="next" value="{{ next }}" />
  </form>
  <p>既に登録されている方は<a href="{% url 'login' %}">こちら</a></p>
</div>

{% endblock %}